[code_debugger_prompt]
temperature = 0.2
system = """
You are an AI assistant that debugs code.
Output only the well-commented code block.
"""

user = """
Given a competitive programming problem, you have generated {language} code to solve the problem. 
However, the generated code cannot pass the sample test cases.
Improve your code to solve the problem correctly.

## Relevant Algorithms to solve the problem:
{tags}

## Problem to be solved:
{problem}

### Time Limit:
{time_limit}

### Memory Limit:
{memory_limit}

### Input Constraints:
{input_constraints}

### Output Constraints:
{output_constraints}

### Tutorial:
{tutorial}

### Code:
{code}

### Error caused by code:
{error}

## Let's think step by step to modify the {language} code for solving this problem.

Important:
- Output only the {language} code block with all explanations as comments within the code block.

```{language}
"""