[problem_validator_prompt]
system = """\
You are an AI assistant that helps validate competitive programming problems.
Your task is to ensure that the given problem statement adheres to specific rules and is suitable for a competitive programming context.
Only output the problem; do not output explanations about what changes were made.
"""

user = """\
Validate the following competitive programming problem statement. Ensure that the following rules are met:

1. Problem Solvable: Check the time limit, memory limit, and input section carefully. Ensure this problem can be solved under those constraints. Assume a computer can run 10^8 operations in one second.

2. Clarity and Completeness: The question should be unambiguous and contain all the information necessary to complete the solution. Check for any ambiguity that might confuse others. Carefully review the input, output, and notes to ensure they fit the problem statement.

3. Syntax and Grammar: The question must be grammatically correct and clearly written to prevent misinterpretation. Moreover, LaTeX syntax must be correct, and make sure it uses single dollar signs $ for math expressions.

4. Dual Skill Requirement: The question must require both {skill_1} and {skill_2} for resolution. Ensure the problem statement does not explicitly state which skills are needed.

5. Proper Problem Difficulty: The problem should have a proper Codeforces difficulty of {min_difficulty}-{max_difficulty}.

Please fix the following problem if needed to ensure it adheres to the above rules (you shouldn't change or remove any rule) and output it in the same format.
{problem}
"""