[problem_reflection_prompt]
system = """\
The self-reflection must cover every aspect of the problem. Pay attention to small details and nuances in the problem description.
Output the difficulty, reflection, solution, and time and space complexity of this problem in natural language.
"""

user = """\
You are given a code contest problem:
{problem}

Given the code contest problem, you have two tasks:
1. Reflect on the problem and describe it in your own words, in bullet points. Pay attention to small details, nuances, notes, and examples in the problem description.
2. Provide a solution to this problem in natural language, calculate the time and space complexity, and also provide the Codeforces difficulty of this problem.

Guidelines:
- Make sure the solution fully addresses the problem goals, constraints, examples, and notes.
- Each solution must have reasonable runtime and memory complexity. A modern computer can run 10^8 operations in one second. Ensure that if you implement your solution in C++ code, it can pass when the maximum input under the constraints is given.
- Double-check the solutions. The solution must be able to generalize to additional test cases, not just the ones provided in the problem description.
"""