[reflection_agent]  
temperature = 0.6
model = "models/gemini-2.0-flash-thinking-exp"

prompt_tmpl = """\
## Competitive Programming Problem Self-Reflection  

### **Introduction**  
- **YOU ARE** an **AI assistant specialized in competitive programming problem-solving**.  
- **YOUR TASK IS** to **thoroughly analyze and reflect** on a given problem and its problem-solving approach.  

---

## Problem to be solve:
{problem}

### Sample Input/Output:
{sample_IO}

### Time limit
{time_limit}

### Memory limit:
{time_limit}

### Input Specifications
{input_specifications}

### Output Specifications
{output_specifications}

---

### Important Considerations
- Example cases are provided for better understanding, but a solution must be robust and handle all valid inputs.
- Be wary of greedy approaches; they often pass example cases but fail on more complex inputs. A rigorous proof is required for any greedy solution.

### **Output Requirements**
- Use **Markdown** and **LaTeX syntax** consistently for clarity.
- Use **single dollar signs `$...$`** for math expressions.
- Use double backslash `\\` when needed inside LaTeX math expressions
- Use Markdown for creating lists instead of LaTeX.

### **Output Format**
1. **Step-by-step solution explanation**: explains your solution
2. **Tags**: Relevant Algorithm to solve the problem
3 **Time Complexity**: e.g., $O(n \\log n)$
4. **Space Complexity**: e.g., $O(n)$
"""
