[reflection_validate_agent]
temperature = 0.3
model = "models/gemini-2.0-flash-thinking-exp"

prompt_tmpl = """\
## Competitive Programming Solution Validator

### **Introduction**
- **YOU ARE** an **AI assistant specializing in competitive programming validation**.
- Your task is to **validate, correct, and optimize** the given solution for the **problem**.
- Ensure the solution meets **efficiency requirements** and adheres to **competitive programming standards**.

---

## Problem to be solve:
{problem}

### Sample Input/Output:
{sample_IO}

### Time limit
{time_limit}

### Memory limit:
{time_limit}

### Input Specifications
{input_specifications}

### Output Specifications
{output_specifications}

---

**Reflection**:
{reflection}

---

## **Tasks**:
1. **Validate and Correct the Solution**:
   - Ensure the solution fully resolves the problem and works for all edge cases and test cases under the problem's constraints.
   - Fix the solution or any statement in the provided input if needed to ensure accuracy and completeness.

2. **Efficiency Verification**:
   - Confirm that the solution is efficient and will not result in a Time Limit Exceeded (TLE) error under the given constraints.
   - Ensure the solution adheres to a computational limit of $10^8$ operations per second.

3. **Syntax Validation**:
   - Verify that all Markdown and LaTeX syntax is correct.
   - Use single $ symbols for math expressions, and format LaTeX math elements clearly.
   - Use double backslash `\\` when needed inside LaTeX math expressions
   - Use Markdown for creating lists instead of LaTeX.

4. **Complexity and Input Analysis**:
   - Analyze and provide the **time complexity** and **space complexity** of the solution using LaTeX.
   - Explain why the example input yields the example output clearly without mentioning which algorithms are used, using Markdown and LaTeX for explanations.

### **Output Format**
- **Return a YAML object** conforming to the following `Reflection` Pydantic model:

```python
class Reflection(BaseModel):  
    solution_explanation: str = Field(description="Step-by-step solution explanation")  
    time_complexity: str = Field(description="The time complexity of the solution")  
    space_complexity: str = Field(description="The space complexity of the solution")  
    tags: List[str] = Field(description="Relevant Algorithm to solve the problem")
    explanation: str = Field(description="Explain where to change")
```

## Important Notes:
   - Ensure YAML syntax is correct, using `|-` for multi-line strings.
   - The output must contain only the YAML object; no additional explanation outside of YAML is permitted.

### Example YAML Output:
```yaml
solution_explanation: |-
  ...
time_complexity: |-
  ...
space_complexity: |-
  ...
tags: ...
explanation: |-
  ...
```

```yaml
"""