[GenProblemWorkflow]
num_of_samples = 5
timeout = 420
verbose = true

[GenSolutionWorkflow]
timeout = 120
verbose = true

[GenTestWorkflow]
timeout = 120
verbose = true

[phoenix]
working_dir = "./phoenix"