[GenProblemWorkflow]
num_of_samples = 10
timeout = 300
verbose = true

[GenReflectionWorkflow]
timeout = 240
verbose = true

[GenSolutionWorkflow]
timeout = 180
verbose = true

[GenTestWorkflow]
timeout = 120
verbose = true

[phoenix]
working_dir = "./phoenix"